### ISSUE TITLE
WASM Support

### ISSUE THREAD

**Issue by Redrield** [brycx/orion#135]
Add support for compiling to wasm32-unknown-unknown and wasm32-wasi,

The only dependency blocking this atm is `getrandom`, because the wasm32-unknown-unknown feature is disabled by default. Adding the "js" feature seems to solve this. I haven't run all the test suites but aead works fine on wasi and wasm32-unknown once this is done.

**Comment by brycx** [comment]
Hi @Redrield 

Thank you for the suggestion! This certainly does sound like something worth adding. I haven't looked in to it but, at a glance, it seems like it can be done without much complication. I'll try get around to it soon, but feel free to open a PR if you've get a working approach.

**Comment by brycx** [comment]
After checking out the documentation of the `js` feature of `getrandom`, `wasm32-wasi` should work out-of-the-box. Only `wasm32-unknown-unknown` should be blocked. Looking at the documentation further, it states
> Instead, if the "js" Cargo feature is enabled, this crate will assume that you are building for an environment containing JavaScript, and will call the appropriate methods.

This assumption is quite important, so we can't enable the `js` feature by default. It most likely needs a separate feature flag. @Redrield, could you maybe tell me more about if you're intending on using Orion with `wasm32-unknown-unknown` somewhere. If yes, what for?

**Comment by vlmutolo** [comment]
All else being equal, I'd definitely prefer to have WASM support feature-gated behind something like a `js` feature, which basically would only enable the `js` feature in the `getrandom` crate. And I'd keep it disabled by default.

**Comment by brycx** [comment]
I'll close this issue for now due to inactivity. If you have further concerns/questions/comments @Redrield, please feel free to re-open it!
