### ISSUE TITLE
Replace uses of T::max_value() with T::MAX

### ISSUE THREAD

**Issue by brycx** [brycx/orion#156]
The max value that a primitive type can represent has been made [accessible](https://doc.rust-lang.org/std/primitive.u32.html#associatedconstant.MAX) as an associated constant. The `max_value()`/`min_value()` functions are soft-deprecated.

```rust
u32::max_value()
```
should change to
```rust
u32::MAX
```

If `T::min_value()` is used anywhere, this should be replaced with `T::MIN`.

Bumps MSRV to 1.43.0.

**Comment by u5surf** [comment]
@brycx 
Hi, I'd like to tackle this issue.
In my grep results, `T::min_value()` is not used anywhere.
```
% grep -rn "T::min_value" ./
%
```

**Comment by brycx** [comment]
@u5sur, you're more than welcome!

And yes, that's the immediate impression I got as well. So, just looking for the maximum should suffice.

**Comment by u5surf** [comment]
@brycx 
Unfortunately, because this MSRV is 1.41.1, It cannot use associated constant directly. From 1.43.0 can use them, or use std::T::MAX

see: 
https://blog.rust-lang.org/2020/04/23/Rust-1.43.0.html

**Comment by brycx** [comment]
Indeed, this requires 1.43.0, as I've mentioned in the description. This is no problem at all.

If you want, you can change the MSRV to 1.43.0, in `tests.yml` in the `.github` folder:

```yml
       rust:
          - stable
          - beta
          - nightly
          - 1.41.0 # MSRV
```
