### ISSUE TITLE
v0.9.1: xchacha20poly1305 always unwraps (missing error propagation)

### ISSUE THREAD

**Issue by ergl** [brycx/orion#40]
Hi, sorry in advance if this is a dumb question. I'm using the default API for encrypt/decrypt. The docs mention that these operations return a `Result`.

However, looking at the implementation, one can see that these functions will panic on Error, as they're calling `.unwrap()` on the `xchacha20poly1305::{encrypt,decrypt}` functions.

https://github.com/brycx/orion/blob/04a0db6d2a2fa387d4499068c0087ef941c2da6a/src/default.rs#L373-L379

https://github.com/brycx/orion/blob/04a0db6d2a2fa387d4499068c0087ef941c2da6a/src/default.rs#L424-L430

As far as I'm aware, this makes it impossible to handle errors in the caller, and will make the application panic.

Is there any way to handle the error, or should `unwrap()` be changed to use the `?` operator?

**Comment by brycx** [comment]
Hi @ergl. 

This is definitely not a dumb question but instead a pretty basic error that I should not have overlooked.
You are indeed right that this makes it impossible to handle errors by the caller. This should be fixed in e0b3e9d and 850f836.

The fix will be included in v0.10, which is planned to be released later today or tomorrow (I'm testing it right now). Note that v0.10 has many changes, including how the high-level API is used.

**Comment by ergl** [comment]
No worries! I'm happy to help. You know the code, so it's only fair, I'd probably have missed some cases.

**Comment by brycx** [comment]
`v0.10` has just been released, so I'm closing this issue. 

Note that the previous `default` API functionality encrypt/decrypt is now located in `orion::aead`. There have been quite a few changes so I suggest skimming the [changelog](https://github.com/brycx/orion/releases/tag/0.10.0). 

Anyway, I really appreciate you reaching out, let me know right away if you run into any problems(or questions) with the new release.

**Comment by brycx** [comment]
Missing error propagation in macro type-definitions: `func_generate`, `construct_secret_key_variable_size` and `construct_salt_variable_size`.

This cannot be done for the `Default` trait implementation because of the trait pattern.
