### ISSUE TITLE
Exception in doc

### ISSUE THREAD

**Issue by hellow554** [brycx/orion#60]
https://github.com/brycx/orion/blob/f5db759f157921c31c571868757900eedd2bcdcf/src/aead.rs#L48-L57

I do not like the word "Exception" here, because Rust doesn't have the term exception in its library, in contrast to other languages, e.g. C#, Java, C++, ...

The Rust documentation ueses the word "Panics" when it will panic under certain conditions (e.g. [`u32::overflowing_div`](https://doc.rust-lang.org/std/primitive.u32.html#panics-1)).

I would suggest to adopt the phrasing.

**Comment by brycx** [comment]
You're right that "Exception" probably isn't the correct phrasing. However, those items listed under "Exceptions" are conditions that, when met, will cause the function to return and `Err` and not directly cause a panic. Perhaps rephrasing to "Errors" would be the most appropriate?

**Comment by hellow554** [comment]
Errors sounds fine to me. 

You want to rephrase the next sentence then to

> An error will be returned if

**Comment by brycx** [comment]
Great! Thank you for the issue @hellow554!
